=== stalep/jboss-aop/aop/docs/jboss-aop_1_0.dtd
<?xml version='1.0' encoding='UTF-8' ?>

<!ELEMENT aop (interceptor|introduction|metadata-loader|metadata|
               stack|aspect|pointcut|pluggable-pointcut|bind|
               prepare|cflow-stack|dynamic-cflow|annotation-introduction|annotation|typedef|domain)+>

<!ELEMENT domain (interceptor|introduction|metadata-loader|metadata|
               stack|aspect|pointcut|pluggable-pointcut|bind|
               prepare|cflow-stack|dynamic-cflow|annotation|annotation-introduction|typedef)+>
<!ATTLIST domain name CDATA #REQUIRED>
<!ATTLIST domain extends CDATA #IMPLIED>
<!ATTLIST domain inheritBindings CDATA #IMPLIED>
<!ATTLIST domain parentFirst CDATA #IMPLIED>


<!ELEMENT interceptor ANY>
<!ATTLIST interceptor name CDATA #IMPLIED>
<!ATTLIST interceptor class CDATA #IMPLIED>
<!ATTLIST interceptor factory CDATA #IMPLIED>
<!ATTLIST interceptor scope (PER_VM|PER_CLASS|PER_INSTANCE|PER_JOINPOINT|PER_CLASS_JOINPOINT) "PER_VM">

<!ELEMENT aspect ANY>
<!ATTLIST aspect name CDATA #IMPLIED>
<!ATTLIST aspect class CDATA #IMPLIED>
<!ATTLIST aspect factory CDATA #IMPLIED>
<!ATTLIST aspect scope (PER_VM|PER_CLASS|PER_INSTANCE|PER_JOINPOINT|PER_CLASS_JOINPOINT) "PER_VM">

<!ELEMENT introduction (mixin*,interfaces)>
<!ATTLIST introduction class CDATA #IMPLIED>
<!ATTLIST introduction expr CDATA #IMPLIED>
<!ELEMENT mixin (interfaces, class, construction?)>
<!ATTLIST mixin transient (true|false) "true">
<!ELEMENT interfaces (#PCDATA)>
<!ELEMENT class (#PCDATA)>
<!ELEMENT construction (#PCDATA)>

<!ELEMENT metadata-loader EMPTY>
<!ATTLIST metadata-loader tag CDATA #REQUIRED>
<!ATTLIST metadata-loader class CDATA #REQUIRED>

<!ELEMENT metadata ANY>
<!ATTLIST metadata tag CDATA #REQUIRED>
<!ATTLIST metadata class CDATA #REQUIRED>

<!ELEMENT stack (interceptor|interceptor-ref|stack-ref|advice)+>
<!ATTLIST stack name CDATA #REQUIRED>

<!ELEMENT interceptor-ref EMPTY>
<!ATTLIST interceptor-ref name CDATA #REQUIRED>

<!ELEMENT stack-ref EMPTY>
<!ATTLIST stack-ref name CDATA #REQUIRED>

<!ELEMENT advice EMPTY>
<!ATTLIST advice name CDATA #REQUIRED>
<!ATTLIST advice aspect CDATA #REQUIRED>

<!ELEMENT pointcut EMPTY>
<!ATTLIST pointcut name CDATA #REQUIRED>
<!ATTLIST pointcut expr CDATA #REQUIRED>

<!ELEMENT prepare EMPTY>
<!ATTLIST prepare expr CDATA #REQUIRED>

<!ELEMENT pluggable-pointcut ANY>
<!ATTLIST pluggable-pointcut name CDATA #REQUIRED>
<!ATTLIST pluggable-pointcut class CDATA #REQUIRED>

<!ELEMENT bind (interceptor|interceptor-ref|stack-ref|advice)+>
<!ATTLIST bind name CDATA #IMPLIED>
<!ATTLIST bind pointcut CDATA #REQUIRED>
<!ATTLIST bind cflow CDATA #IMPLIED>

<!ELEMENT cflow-stack (called|not-called)+>
<!ATTLIST cflow-stack name CDATA #REQUIRED>

<!ELEMENT called EMPTY>
<!ATTLIST called expr CDATA #REQUIRED>
<!ELEMENT not-called EMPTY>
<!ATTLIST not-called expr CDATA #REQUIRED>


<!ELEMENT dynamic-cflow EMPTY>
<!ATTLIST dynamic-cflow name CDATA #REQUIRED>
<!ATTLIST dynamic-cflow class CDATA #REQUIRED>

<!ELEMENT annotation-introduction (#PCDATA)>
<!ATTLIST annotation-introduction expr CDATA #REQUIRED>
<!ATTLIST annotation-introduction invisible (true|false) #REQUIRED>

<!ELEMENT annotation (#PCDATA)>
<!ATTLIST annotation expr CDATA #REQUIRED>

<!ELEMENT typedef EMPTY>
<!ATTLIST typedef name CDATA #REQUIRED>
<!ATTLIST typedef expr CDATA #REQUIRED>

=== stalep/jboss-aop/aop/src/resources/test/instanceofannotated/jboss-aop.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aop SYSTEM "jboss-aop_1_0.dtd">

<aop>
   
   <interceptor name="CountingInterceptor" class="org.jboss.test.aop.instanceofannotated.CountingInterceptor"/>

   <bind pointcut="execution(void $instanceof{@org.jboss.test.aop.instanceofannotated.InterfaceAnnotation}->annotatedMethod())">
      <interceptor-ref name="CountingInterceptor"/>
   </bind>
      
   <bind pointcut="execution(void $instanceof{@org.jboss.test.aop.instanceofannotated.InterfaceAnnotation}->otherAnnotatedMethod())">
      <interceptor-ref name="CountingInterceptor"/>
   </bind>
      
   <bind pointcut="execution(int $instanceof{@org.jboss.test.aop.instanceofannotated.ClassAnnotation}->superClassMethod())">
      <interceptor-ref name="CountingInterceptor"/>
   </bind>

   <introduction expr="class($instanceof{@org.jboss.test.aop.instanceofannotated.ClassAnnotation})">
      <interfaces>
         org.jboss.test.aop.instanceofannotated.EmptyInterface
      </interfaces>
   </introduction>
   
   <bind pointcut="execution($instanceof{org.jboss.test.aop.instanceofannotated.interfaces.*}->new())">
      <interceptor-ref name="CountingInterceptor"/>
   </bind>

   <bind pointcut="execution(void $instanceof{org.jboss.test.aop.instanceofannotated.*}->someMethod())">
      <interceptor-ref name="CountingInterceptor"/>
   </bind>

   <bind pointcut="execution(void $instanceof{*.SomeInterface}->otherMethod())">
      <interceptor-ref name="CountingInterceptor"/>
   </bind>

   <bind pointcut="execution(void $instanceof{org.*.SomeInterface}->anotherMethod())">
      <interceptor-ref name="CountingInterceptor"/>
   </bind>

   <typedef name="td" expr="class(org.jboss.test.aop.instanceofannotated.Type)"/>

   <bind pointcut="call(org.jboss.test.aop.instanceofannotated.POJO->new($typedef{td}, $instanceof{org.jboss.test.aop.instanceofannotated.SuperType}, int))">
      <interceptor-ref name="CountingInterceptor"/>
   </bind>

   <bind pointcut="execution(org.jboss.test.aop.instanceofannotated.POJO->new($typedef{td}, $instanceof{org.jboss.test.aop.instanceofannotated.SuperType}, int))">
      <interceptor-ref name="CountingInterceptor"/>
   </bind>

   <bind pointcut="execution($typedef{td} org.jboss.test.aop.instanceofannotated.POJO->paramsAndTypedefReturn($typedef{td}, $instanceof{org.jboss.test.aop.instanceofannotated.SuperType}, int))">
      <interceptor-ref name="CountingInterceptor"/>
   </bind>

   <bind pointcut="call($typedef{td} org.jboss.test.aop.instanceofannotated.POJO->paramsAndTypedefReturn($typedef{td}, $instanceof{org.jboss.test.aop.instanceofannotated.SuperType}, int))">
      <interceptor-ref name="CountingInterceptor"/>
   </bind>

   <bind pointcut="execution($instanceof{org.jboss.test.aop.instanceofannotated.SuperType} org.jboss.test.aop.instanceofannotated.POJO->paramsAndInstanceofReturn($typedef{td}, $instanceof{org.jboss.test.aop.instanceofannotated.SuperType}, int))">
      <interceptor-ref name="CountingInterceptor"/>
   </bind>

   <bind pointcut="field($instanceof{org.jboss.test.aop.instanceofannotated.SuperType} $instanceof{org.jboss.test.aop.instanceofannotated.POJO}->instanceofField)">
      <interceptor-ref name="CountingInterceptor"/>
   </bind>

   <bind pointcut="field($typedef{td} org.jboss.test.aop.instanceofannotated.POJO->typedefField)">
      <interceptor-ref name="CountingInterceptor"/>
   </bind>

   <typedef name="ip" expr="class(org.jboss.test.aop.instanceofannotated.IntroducedPOJO)"/>

   <annotation-introduction expr="class($typedef{ip})">
      @org.jboss.test.aop.instanceofannotated.Introduced
   </annotation-introduction>

   <annotation-introduction expr="constructor($instanceof{@org.jboss.test.aop.instanceofannotated.Annotation}->new($typedef{td}, $instanceof{@org.jboss.test.aop.instanceofannotated.TypeAnnotation}))">
      @org.jboss.test.aop.instanceofannotated.Introduced
   </annotation-introduction>
   
   <annotation-introduction expr="constructor($typedef{ip}->new($typedef{td}, $instanceof{@org.jboss.test.aop.instanceofannotated.TypeAnnotation}) throws java.lang.Exception)">
      @org.jboss.test.aop.instanceofannotated.Introduced2
   </annotation-introduction>
   
   <annotation-introduction expr="constructor($typedef{ip}->new($typedef{td}, $instanceof{@org.jboss.test.aop.instanceofannotated.TypeAnnotation}) throws java.io.IOException)">
      @org.jboss.test.aop.instanceofannotated.Introduced3
   </annotation-introduction>
   
   <annotation-introduction expr="method($typedef{td} $typedef{ip}->someMethod($typedef{td}, $instanceof{@org.jboss.test.aop.instanceofannotated.TypeAnnotation}))">
      @org.jboss.test.aop.instanceofannotated.Introduced
   </annotation-introduction>
   
   <annotation-introduction expr="method($instanceof{@org.jboss.test.aop.instanceofannotated.TypeAnnotation} $typedef{ip}->someMethod($typedef{td}, $instanceof{@org.jboss.test.aop.instanceofannotated.TypeAnnotation}) throws java.lang.Exception)">
      @org.jboss.test.aop.instanceofannotated.Introduced2
   </annotation-introduction>
   
   <annotation-introduction expr="method($instanceof{@org.jboss.test.aop.instanceofannotated.TypeAnnotation} $typedef{ip}->someMethod($typedef{td}, $instanceof{@org.jboss.test.aop.instanceofannotated.TypeAnnotation}) throws java.io.IOException)">
      @org.jboss.test.aop.instanceofannotated.Introduced3
   </annotation-introduction>
   
   <annotation-introduction expr="field($typedef{td} $typedef{ip}->field)">
      @org.jboss.test.aop.instanceofannotated.Introduced
   </annotation-introduction>

   <annotation-introduction expr="field($instanceof{@org.jboss.test.aop.instanceofannotated.TypeAnnotation} $instanceof{@org.jboss.test.aop.instanceofannotated.Annotation}->field)">
      @org.jboss.test.aop.instanceofannotated.Introduced2
   </annotation-introduction>
   
   
</aop>

=== stalep/jboss-aop/aop/src/resources/test/extender/jboss-aop.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE aop PUBLIC
   "-//JBoss//DTD JBOSS AOP 1.0//EN"
   "http://www.jboss.org/aop/dtd/jboss-aop_1_0.dtd">

<aop>

	<aspect class="org.jboss.test.aop.extender.SuperCallAspect"/>
   <prepare expr="all(org.jboss.test.aop.extender.Base)"/>
   <prepare expr="all(org.jboss.test.aop.extender.Extender)"/>
   <bind pointcut="execution(* org.jboss.test.aop.extender.ChildBase->updateBase())">
      <interceptor class="org.jboss.test.aop.extender.ExtenderInterceptor"/>
   </bind>
   
   <bind pointcut="execution(* org.jboss.test.aop.extender.Base->setBase(..))">
      <interceptor class="org.jboss.test.aop.extender.ExtenderInterceptor"/>
   </bind>
   
   <bind pointcut="execution(* org.jboss.test.aop.extender.ChildExtender->*(..))">
      <interceptor class="org.jboss.test.aop.extender.ExtenderInterceptor"/>
   </bind>
   
   <bind pointcut="execution(* org.jboss.test.aop.extender.InfantBase->*(..))">
      <interceptor class="org.jboss.test.aop.extender.ExtenderInterceptor"/>
   </bind>
   
   <bind pointcut="execution(* $instanceof{org.jboss.test.aop.extender.Base}->superCall())">
   	<advice aspect="org.jboss.test.aop.extender.SuperCallAspect" name="invoke"/>
   </bind>
   <bind pointcut="execution(* org.jboss.test.aop.extender.Base->superCall())">
   	<advice aspect="org.jboss.test.aop.extender.SuperCallAspect" name="invoke"/>
   </bind>
</aop>
